name: OPA Policy Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  OPA_VERSION: v1.7.1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: ${{ env.OPA_VERSION }}
    
    - name: Validate OPA Version
      run: |
        opa version
        opa_version=$(opa version | grep "Version:" | awk '{print $2}')
        echo "OPA Version: $opa_version"
    
    - name: Validate Policy Syntax
      run: |
        echo "Checking policy formatting..."
        for policy in $(find policies -name "*.rego"); do
          echo "Validating $policy"
          opa fmt --diff $policy || exit 1
        done
    
    - name: Run OPA Tests with Coverage
      run: |
        echo "Running policy tests with coverage..."
        opa test policies/ tests/ -v --coverage --format json | tee test-results.json
    
    - name: Generate Coverage Report
      run: |
        coverage=$(cat test-results.json | jq '.coverage // 0')
        echo "Test coverage: ${coverage}%"
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "Coverage: ${coverage}%" >> $GITHUB_STEP_SUMMARY
        if (( $(echo "$coverage < 80" | bc -l) )); then
          echo "⚠️ Test coverage is below 80%" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
    
    - name: Run Policy Benchmarks
      run: |
        echo "Running policy benchmarks..."
        if [ -f "benchmarks/bench.yaml" ]; then
          opa bench -d policies/ -b benchmarks/bench.yaml --format json | tee bench-results.json
        fi
    
    - name: Validate Bundle Structure
      run: |
        echo "Building and validating OPA bundle..."
        opa build -b policies/ -o bundle.tar.gz
        tar -tzf bundle.tar.gz
        echo "✓ Bundle created successfully"
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results.json
          bench-results.json
    
    - name: Upload Bundle
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: policy-bundle
        path: bundle.tar.gz